- hosts: localhost
  connection: local
  gather_facts: Flase
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state : "{{state}}"
      register: vpcout

    - debug:
        var: vpcout


#here register will store all data in vpcout i.e, output will store in vpcout

#creating a public subnet 1 in zone1

    - name: create a public subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out
